version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: setuptools
    versions:
    - 53.1.0
    - 54.0.0
    - 54.1.1
    - 54.1.2
    - 54.2.0
  - dependency-name: pandas
    versions:
    - 1.2.2
    - 1.2.3
  - dependency-name: numpy
    versions:
    - 1.20.1
  - dependency-name: mongoengine
    versions:
    - 0.22.1
