name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1      
      with:
        python-version: 3.8
        #python-root-list: 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        cd src/argparse 
        pylint `ls -R|grep .py$|xargs`
        cd src/async 
        pylint `ls -R|grep .py$|xargs`
        cd src/concurrency 
        pylint `ls -R|grep .py$|xargs`
        cd src/ipaddress 
        pylint `ls -R|grep .py$|xargs`
        cd src/sockets 
        pylint `ls -R|grep .py$|xargs`
        cd src/sort 
        pylint `ls -R|grep .py$|xargs`
        cd src/threads 
        pylint `ls -R|grep .py$|xargs`
        cd src/tricks